### ISSUE TITLE
Labels in Html::activeDropDownList doesn't work

### ISSUE THREAD

**Issue by SimonVonDerGoltz** [MacGyer/yii2-materializecss#52]
If you have two Dropdowns on top of each other, the one at the bottom has no label (it's somewhere behind the nav).

**Comment by MacGyer** [comment]
This behavior occurs, because it has been styled by Materialize this way:

```scss
.select-wrapper {
  ...
  & + label {
    position: absolute;
    top: -26px;
    font-size: $label-font-size;
  }
  ...
}
```

So this issue has to be delegated to the Materialize project: https://github.com/materializecss/materialize/issues
